// 添加示例图片数据
export const demoImages = {
  banner: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800',
  products: [
    'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=400',
    'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400',
    'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400',
    'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=400',
    'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400',
    'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400',
  ],
  categories: [
    'https://images.unsplash.com/photo-1526947425960-945c6e72858f?w=400',
    'https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?w=400',
    'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=400',
    'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400',
  ],
};

// 模拟商品数据
export const products = [
  {
    id: 'xxxxxxxx',
    name: '时尚休闲连帽卫衣',
    image: demoImages.products[0],
    price: 89.99,
    profitMargin: 45,
    minOrder: 50,
    shippingTime: '3-5天',
    supplier: {
      name: '优品服饰',
      rating: 4.8,
      logo: '/images/suppliers/fashion.jpg',
    },
    description: '采用优质面料，舒适保暖，时尚百搭',
    origin: '中国',
    suggestedPrice: 129.99,
    shopUrl: '/products/hoodie',
    categoryId: '3-301', // 服装鞋帽-男装
  },
  {
    id: '2',
    name: '智能手表健康监测',
    image: demoImages.products[1],
    price: 299.99,
    profitMargin: 35,
    minOrder: 20,
    shippingTime: '2-4天',
    supplier: {
      name: '科技先锋',
      rating: 4.9,
      logo: '/images/suppliers/tech.jpg',
    },
    description: '多功能健康监测，高清显示屏，续航持久',
    origin: '中国',
    suggestedPrice: 399.99,
    shopUrl: '/products/smartwatch',
    categoryId: '1-103', // 电子产品-智能设备
  },
  {
    id: '3',
    name: '高端蓝牙耳机',
    image: demoImages.products[2],
    price: 159.99,
    profitMargin: 40,
    minOrder: 30,
    shippingTime: '3-5天',
    supplier: {
      name: '音频专家',
      rating: 4.7,
      logo: '/images/suppliers/audio.jpg',
    },
    description: '主动降噪，高品质音质，舒适佩戴',
    origin: '中国',
    suggestedPrice: 199.99,
    shopUrl: '/products/headphones',
  },
  {
    id: '4',
    name: '便携式移动电源',
    image: demoImages.products[3],
    price: 79.99,
    profitMargin: 50,
    minOrder: 100,
    shippingTime: '2-3天',
    supplier: {
      name: '电子科技',
      rating: 4.6,
      logo: '/images/suppliers/electronics.jpg',
    },
    description: '大容量快充，多口输出，轻薄便携',
    origin: '中国',
    suggestedPrice: 99.99,
    shopUrl: '/products/powerbank',
  },
  {
    id: '5',
    name: '时尚休闲连帽卫衣',
    image: demoImages.products[0],
    price: 89.99,
    profitMargin: 45,
    minOrder: 50,
    shippingTime: '3-5天',
    supplier: {
      name: '优品服饰',
      rating: 4.8,
      logo: '/images/suppliers/fashion.jpg',
    },
    description: '采用优质面料，舒适保暖，时尚百搭',
    origin: '中国',
    suggestedPrice: 129.99,
    shopUrl: '/products/hoodie',
  },
  {
    id: '6',
    name: '智能手表健康监测',
    image: demoImages.products[1],
    price: 299.99,
    profitMargin: 35,
    minOrder: 20,
    shippingTime: '2-4天',
    supplier: {
      name: '科技先锋',
      rating: 4.9,
      logo: '/images/suppliers/tech.jpg',
    },
    description: '多功能健康监测，高清显示屏，续航持久',
    origin: '中国',
    suggestedPrice: 399.99,
    shopUrl: '/products/smartwatch',
  },
  {
    id: '7',
    name: '高端蓝牙耳机',
    image: demoImages.products[2],
    price: 159.99,
    profitMargin: 40,
    minOrder: 30,
    shippingTime: '3-5天',
    supplier: {
      name: '音频专家',
      rating: 4.7,
      logo: '/images/suppliers/audio.jpg',
    },
    description: '主动降噪，高品质音质，舒适佩戴',
    origin: '中国',
    suggestedPrice: 199.99,
    shopUrl: '/products/headphones',
  },
  {
    id: '8',
    name: '便携式移动电源',
    image: demoImages.products[3],
    price: 79.99,
    profitMargin: 50,
    minOrder: 100,
    shippingTime: '2-3天',
    supplier: {
      name: '电子科技',
      rating: 4.6,
      logo: '/images/suppliers/electronics.jpg',
    },
    description: '大容量快充，多口输出，轻薄便携',
    origin: '中国',
    suggestedPrice: 99.99,
    shopUrl: '/products/powerbank',
  },
];

// 模拟分类数据
export const categories = [
  {
    id: 1,
    name: '电子产品',
    image: demoImages.categories[0],
    count: 1280,
    children: [
      { id: 101, name: '手机数码', count: 450 },
      { id: 102, name: '电脑配件', count: 380 },
      { id: 103, name: '智能设备', count: 450 },
    ],
  },
  {
    id: 2,
    name: '家居用品',
    image: demoImages.categories[1],
    count: 856,
    children: [
      { id: 201, name: '家具装饰', count: 320 },
      { id: 202, name: '厨房用品', count: 286 },
      { id: 203, name: '生活日用', count: 250 },
    ],
  },
  {
    id: 3,
    name: '服装鞋帽',
    image: demoImages.categories[2],
    count: 2150,
    children: [
      { id: 301, name: '男装', count: 860 },
      { id: 302, name: '女装', count: 950 },
      { id: 303, name: '童装', count: 340 },
    ],
  },
  {
    id: 4,
    name: '美妆护肤',
    image: demoImages.categories[3],
    count: 960,
    children: [
      { id: 401, name: '护肤品', count: 420 },
      { id: 402, name: '彩妆', count: 380 },
      { id: 403, name: '香水', count: 160 },
    ],
  },
];
